upload static gpt demo
PaddlePaddle/PaddleFleetX pull request #531
Opened 2021-08-18 03:54 UTC by youth123

upload static gpt demo

2021-08-18 04:12 UTC, sandyhouse requested changes

2021-08-18 04:12 UTC, sandyhouse commented on examples/static/gpt/run_static_mp.sh
> +set -x
把run_static_dp_mp.sh run_static_dp_mp.sh run_static_dp.sh整合成run_static.sh一个文件吧，通过参数控制运行哪种模式。

2021-08-18 04:12 UTC, sandyhouse commented on examples/static/paddlenlp/transformers/.ipynb_checkpoints/__init__-checkpoint.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
What's this file for?

2021-08-18 04:12 UTC, sandyhouse commented on examples/static/paddlenlp/transformers/.ipynb_checkpoints/attention_utils-checkpoint.py
> +#   Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
What's this file for?

2021-08-18 04:12 UTC, sandyhouse commented on examples/static/paddlenlp/transformers/gpt/.ipynb_checkpoints/modeling-checkpoint.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
What's this file for?

2021-08-18 04:12 UTC, sandyhouse commented on examples/static/paddlenlp/transformers/gpt/modeling_auto.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
Is this file necessary?

2021-08-18 04:12 UTC, sandyhouse commented on examples/static/paddlenlp/transformers/gpt/modeling_serial.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
整合modeling_manual.py和modeling_serial.py为一个文件？

2021-08-18 04:18 UTC, youth123 commented on examples/static/paddlenlp/transformers/.ipynb_checkpoints/__init__-checkpoint.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
Dummy files.

2021-08-18 06:01 UTC, youth123 commented on examples/static/paddlenlp/transformers/.ipynb_checkpoints/__init__-checkpoint.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
I forget to add gitignore file.

2021-09-24 07:49 UTC, sandyhouse approved these changes

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/README.md
> +本项目是语言模型 GPT 的 PaddlePaddle 实现，FOR CE。
去掉For CE吧。我们这个是参考代码，兼备支持CE测试，但不仅仅是为了CE。

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/README.md
> +sh run_static.sh mp "0,1"
仅仅指定mp、pp等策略的话，用户怎么指定具体的并行度呢? 比如2卡mp，还是4卡mp。

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/args.py
> +        help="Model type selected in the list: " )
list为空？可以后面补充上。

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/args.py
> +        help="Path to pre-trained model or shortcut name selected in the list: ")
同上。

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/args.py
> +        help="Sharding degree. Share the parameters to many cards.")
Share --> Shard

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/README.md
> +```
后面可以补充下各个参数的含义。

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/dataset.py
> +                                      args.max_steps * topo.data_info.size)
For pipeline, should we use args.micro_batch_size*args.max_steps*topo.data_info.size*num_micro_batches?

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/dataset.py
> +    if worker_index == 0:
如果是多机训练，其它节点是不是就拿不到数据了。这个地方是否应该为worker_index % gpus_per_nodes == 0?

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/global_setting.py
> +    global ROOT_MESH
The above two statements are unnecessary for hybrid-parallelism.

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling.py
> +            auto.shard_tensor(
Why use shard_tensor api for auto parallelel?

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling.py
> +            auto.shard_tensor(
why use shard_tensor?

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling.py
> +                dim_mapping=[1, -1])
why use shard_tensor?

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling.py
> +                self.linear1.weight, global_setting._global_process_mesh,
why use shard_tensor?

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling.py
> +                global_setting._global_process_mesh,
why use shard_tensor?

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling_utils/data/iterator.py
> +# Iterator for NLP Dataset
What does this file for?

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling_utils/transformers/generation_utils.py
> +        return logits
这个文件有用到吗？

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling_utils/transformers/gpt/modeling.py
> +        # layers.Print(tgt, message="norm2 after")
Delete these commented statements。

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling_utils/transformers/gpt/modeling_auto.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
删掉这个文件吧，手动混合并行里面不要混入自动并行的。

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling_utils/transformers/gpt/modeling_manual.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
modeling.py model_manual.py这两个文件什么区别?

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling_utils/transformers/gpt/modeling_serial.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
该文件需要吗？

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling_utils/transformers/transformer/modeling.py
> +        enc_output = self.transformer.encoder(enc_input, src_slf_attn_bias)
这个文件是必要的吗？

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/modeling_utils/utils/downloader.py
> +     'https://bert-models.bj.bcebos.com/cased_L-24_H-1024_A-16.tar.gz'),
这个文件是必要的吗？

2021-09-24 07:49 UTC, sandyhouse commented on examples/static/gpt/test_hybrid_parallel.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
What does this file for？

2021-09-24 07:50 UTC, merged