init
PaddlePaddle/PaddleFleetX pull request #838
Opened 2022-10-19 08:58 UTC by fengxiaoshuai

inference vit

2022-10-19 09:26 UTC, GuoxiaWang commented
现在是已经统一区分 inference 文档了吗？还是每个任务中的文档有训练，也有导出，推理等等，全流程。

2022-10-24 12:35 UTC, qingqing01 commented
@GuoxiaWang 看起来推理示例、文档放到 https://github.com/PaddlePaddle/PaddleFleetX/tree/develop/projects/vit 这个后面？

2022-10-24 12:47 UTC, GuoxiaWang commented
@qingqing01 我不太清楚，但是从我个人观点看，展现给用户可能是以模型一站式服务，所以用户定位到模型的时候，可能就能从数据处理，到预训练，finetune，量化，模型导出，python 推理，部署等等全流程视角看到？

2022-11-02 02:19 UTC, GuoxiaWang requested changes

2022-11-02 02:19 UTC, GuoxiaWang commented on projects/vit/README.md
> +    -c ppfleetx/configs/vis/vit/ViT_base_patch16_224_pt_in1k_2n16c_dp_fp16o2.yaml \
路径写错了

2022-11-02 02:19 UTC, GuoxiaWang commented on projects/vit/README.md
> +python projects/vit/inference.py -c ppfleetx/configs/vis/vit/ViT_base_patch16_224_pt_in1k_2n16c_dp_fp16o2.yaml
同理路径写错了

2022-11-02 02:19 UTC, GuoxiaWang commented on ppfleetx/configs/vis/vit/ViT_base_patch16_224_inference.yaml
> +    shape_range_info_filename: ./shape.pbtxt
要不直接把这些字段加到训练的 yaml 文件中吧

2022-11-07 08:50 UTC, GuoxiaWang approved these changes
LGTM

2022-11-07 08:50 UTC, GuoxiaWang commented on projects/vit/README.md
> +python projects/vit/inference_vit.py -c ppfleetx/configs/vis/vit/ViT_base_patch16_224_inference.yaml
这里是不是稍了一个结尾 ```?

2022-11-07 09:18 UTC, fengxiaoshuai commented on projects/vit/README.md
> +python projects/vit/inference_vit.py -c ppfleetx/configs/vis/vit/ViT_base_patch16_224_inference.yaml
> 这里是不是稍了一个结尾 ```?

已经添加

2022-11-07 09:32 UTC, merged